In [8]:
import numpy as np
np.arange(100,200,10).reshape(5,2)

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [12]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
sampleArray[:,2]

array([33, 66, 99])

In [20]:
mat1=np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]))
print(mat1)
mat1[0::2,1::2]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [21]:
mat1=np.array([[1,2,3],[4,5,6]])
mat2=np.array([[1,2,3],[4,5,8]])
mat3=mat1+mat2
print(mat3)
print(mat3**2)

[[ 2  4  6]
 [ 8 10 14]]
[[  4  16  36]
 [ 64 100 196]]


In [24]:
mat=np.arange(10,34).reshape(8,3)
print(mat)
np.split(mat,4)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]


[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

In [2]:
import numpy as np
arr=np.ndarray(shape=(3,4),dtype=int)
m=arr.shape[0]
n=arr.shape[1]
print("Enter the elements:")
for i in range(m):
    for j in range(n):
        arr[i,j]=int(input())
        
    
print(arr)
    

Enter the elements:
23
45
34
56
78
89
76
56
23
98
97
80
[[23 45 34 56]
 [78 89 76 56]
 [23 98 97 80]]
